const lessonTitle = "阿豺折箭";

const lessonData = [
    // ===== 第1段 =====
    ["阿豺", "ā chái", "Achai", "Achai", "阿豺"],
    ["有子", "yǒu zǐ", "had sons", "mempunyai anak", "有儿子"],
    ["二十人", "èr shí rén", "twenty sons", "dua puluh orang", "二十人"],
    ["，", "", "", "", ""],
    ["及老", "jí lǎo", "as he grew old", "setelah tua", "到年老时"],
    ["，", "", "", "", ""],
    ["临终", "lín zhōng", "on his deathbed", "di saat akhir hayat", "临死前"],
    ["谓子", "wèi zǐ", "said to his sons", "berkata kepada anak-anaknya", "对儿子们说"],
    ["曰", "yuē", "", "", "道"],
    ["：", "", "", "", ""],
    ["“", "", "", "", ""],
    ["汝等", "rǔ děng", "You each", "Kamu semua", "你们"],
    ["各", "gè", "each", "masing-masing", "各自"],
    ["奉", "fèng", "hold", "pegang", "拿着"],
    ["吾", "wú", "my", "saya", "我的"],
    ["一只箭", "yī zhī jiàn", "one arrow", "sebatang anak panah", "一支箭"],
    ["，", "", "", "", ""],
    ["折之", "zhé zhī", "break it", "patahkannya", "把它折断"],
    ["地下", "dì xià", "on the ground", "di tanah", "在地上"],
    ["。”", "", "", "", ""],
    ["俄而", "é ér", "Soon after", "Tidak lama kemudian", "不久"],
    ["命", "mìng", "ordered", "menyuruh", "命令"],
    ["母弟", "mǔ dì", "younger brother (of the same mother)", "adik lelaki (seibu)", "同母之弟"],
    ["慕利延", "mù lì yán", "Muliyan", "Muliyan", "慕利延"],
    ["曰", "yuē", "saying", "berkata", "说"],
    ["：", "", "", "", ""],
    ["“", "", "", "", ""],
    ["汝", "rǔ", "You", "Kamu", "你"],
    ["取", "qǔ", "take", "ambil", "拿取"],
    ["一只箭", "yī zhī jiàn", "one arrow", "sebatang anak panah", "一支箭"],
    ["折之", "zhé zhī", "break it", "patahkannya", "把它折断"],
    ["。”", "", "", "", ""],
    ["慕利延", "mù lì yán", "Muliyan", "Muliyan", "慕利延"],
    ["折之", "zhé zhī", "broke it", "mematahkannya", "把它折断"],
    ["。", "", "", "", ""],
    ["又", "yòu", "Again", "Lagi", "又"],
    ["曰", "yuē", "said", "berkata", "说"],
    ["：", "", "", "", ""],
    ["“", "", "", "", ""],
    ["汝", "rǔ", "You", "Kamu", "你"],
    ["取", "qǔ", "take", "ambil", "拿取"],
    ["十九只箭", "shí jiǔ zhī jiàn", "nineteen arrows", "sembilan belas batang anak panah", "十九支箭"],
    ["折之", "zhé zhī", "break them", "patahkannya", "把它们折断"],
    ["。”", "", "", "", ""],
    ["延", "yán", "Muliyan", "Muliyan", "慕利延"],
    ["不能折", "bù néng zhé", "could not break them", "tidak dapat mematahkannya", "不能折断"],
    ["。", "", "", "", ""],
    ["阿豺", "ā chái", "Achai", "Achai", "阿豺"],
    ["曰", "yuē", "said", "berkata", "说"],
    ["：", "", "", "", ""],
    ["“", "", "", "", ""],
    ["汝曹", "rǔ cáo", "You all", "Kamu semua", "你们"],
    ["知否", "zhī fǒu", "do you know", "tahukah kamu", "知道吗"],
    ["？", "", "", "", ""],
    ["单者", "dān zhě", "A single one", "Yang sebatang", "单个的东西"],
    ["易折", "yì zhé", "is easily broken", "mudah patah", "容易折断"],
    ["，", "", "", "", ""],
    ["众则", "zhòng zé", "many then", "berbilang maka", "多则"],
    ["难摧", "nán cuī", "is hard to destroy", "sukar dihancurkan", "难以摧毁"],
    ["。", "", "", "", ""],
    ["戮力一心", "lù lì yī xīn", "unite efforts and hearts", "bersatu hati dan tenaga", "同心合力"],
    ["，", "", "", "", ""],
    ["然后", "rán hòu", "then only", "barulah", "这样之后"],
    ["社稷", "shè jì", "the state", "negara", "国家"],
    ["可固也", "kě gù yě", "can be stable", "dapat kukuh", "可以稳固"],
    ["。”", "", "", "", ""],
    ["言终", "yán zhōng", "Having said this", "Setelah berkata demikian", "话说完"],
    ["而死", "ér sǐ", "he died", "dia meninggal", "就去世了"],
    ["。", "", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", "", ""],
    ["魏收", "wèi shōu", "Wei Shou", "Wei Shou", "魏收"],
    ["《", "", "", "", ""],
    ["阿豺折箭", "ā chái zhé jiàn", "Achai Breaks Arrows", "Achai Mematahkan Anak Panah", "阿豺折箭"],
    ["》", "", "", "", ""],
    ["，", "", "", "", ""],
    ["有", "yǒu", "with", "ada", "有"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai", "改动"],
    ["）", "", "", "", ""]
];
